navyu_slam_node:
  ros__parameters:
    width: 4000
    height: 4000
    resolution: 0.05
    odom_frame_id: odom
    robot_frame_id: base_link
    displacement: 0.1
    probability_occ: 0.9
    probability_free: 0.25
