navyu_slam_node:
  ros__parameters:
    map_frame_id: map
    odom_frame_id: odom
    robot_frame_id: base_link
    map_generator:
      probability_occ: 0.8
      probability_free: 0.2
      leaf_size: 0.05
      displacement: 0.1
      resolution: 0.05
    use_odom: true
    map_publish_interval: 0.5
